- neo-cli/Services/ConsoleServiceBase.cs
- neo-cli/neo-cli.csproj
updated to netcoreapp 2.0
CLI is now color, and the color was not reset on exit.
> reset the console color

- neo-cli/Shell/MainService.cs
Show wallet height when executing "show state" command. Keep in line with neo-gui.
> Show wallet height when executing "show state" command

- ci/README.md
- ci/test-neo-cli.expect
* More documentation, also how to run tests manually.
* Added a small fix for occasionally failing expect tests
> ci/README.md: doc updates and ci/expect bugfix

- README.md
Here's how it looks: https://github.com/metachris/neo-cli/tree/readme-travis
Edit: Not sure if you want this, it's just meant as a proposal/idea ^^
> README.md: added Travis-CI badge

- neo-cli/Network/RPC/RpcServerWithWallet.cs
> add RPC command `listaddress`

- README.md
Added a reference to the plugins project in order to help people to enable logging (I sent a PR to this repository including a readme)
> Adding plugin reference

- neo-cli/Shell/MainService.cs
- neo-cli/neo-cli.csproj
- Allow loaded plugins.
- Call plugins help.
(Needs https://github.com/neo-project/neo/pull/466)
> Add plugins help

- neo-cli/Shell/Coins.cs
- neo-cli/Shell/MainService.cs
Provide a parameter option to save the claimed gas to a specific address, meanwhile the password is needed in this case.
> Add change address option to claim gas [all]

- neo-cli/Shell/MainService.cs
#286 broke the `show state` command on Linux. This is one way to fix it.
> Fix show state command on Linux.

- neo-cli/Shell/MainService.cs
Fix https://github.com/neo-project/neo-cli/issues/315
> Fix for #315

- neo-cli/Settings.cs
- neo-cli/Shell/MainService.cs
> Add `MaxGasInvoke` to `Settings`

- neo-cli/Shell/MainService.cs
Close https://github.com/neo-project/neo-cli/issues/312
> Show the script hash on deploy

- neo-cli/Shell/MainService.cs
> Fix the policy of extra fee

- neo-cli/Shell/MainService.cs
Add the calculation of extra gas fee for "send" function.
> Add the calculation of extra gas fee for "send" function.

- neo-cli/Shell/MainService.cs
> fix size calculation

- neo-cli/Shell/MainService.cs
support https://github.com/neo-project/neo/pull/673
> use LastBlockIndex in show state

- neo-cli/Shell/MainService.cs
Fix multisig transaction failure
> Fix multisig transaction failure

- neo-cli/Shell/MainService.cs
Add default case for broadcast command, prevent unexpected errors.
> Fix broadcast miss default case

- neo-cli/Shell/MainService.cs
Close https://github.com/neo-project/neo-plugins/issues/95
> Fix install plugin 2x

- neo-cli/Shell/MainService.cs
Close https://github.com/neo-project/neo-cli/issues/367#issuecomment-494521402
> Show error when PluginURL is not defined (3x)

- neo-cli/Shell/MainService.cs
Close https://github.com/neo-project/neo-cli/issues/367#issuecomment-494521402
> Show error when PluginURL is not defined (2x)

- neo-cli/Shell/MainService.cs
Close https://github.com/neo-project/neo-cli/issues/366
> Fix uninstall CoreMetrics (2x)

- neo-cli/Shell/MainService.cs
Close https://github.com/neo-project/neo-cli/issues/366
> Fix uninstall CoreMetrics (3x)

- neo-cli/protocol.testnet.json
> Fix LowPriorityThreshold

- neo-cli/Shell/MainService.cs
Same as https://github.com/neo-project/neo-cli/pull/376 but for neo3
> Fix uninstall plugin (3x)

- neo-cli/Shell/MainService.cs
> Opening the wallet with RPC turned on requires user confirmation

- neo-cli/Shell/MainService.cs
> Fix cancellation error

- README.md
- neo-cli/Shell/MainService.cs
- neo-cli/neo-cli.csproj
> Add --testnet and --mainnet param option

- neo-cli/Shell/MainService.cs
Improvement on '''listing asset''' to display more critical info on NEO3.
> Improvement on '''list asset''' for details

- Dockerfile
- README.md
Support build neo-cli into docker image(https://github.com/neo-project/neo-cli/issues/304).
> Feature dockerfile

- neo-cli/Shell/MainService.cs
- neo-cli/neo-cli.csproj
> resolve #435

- neo-cli/Settings.cs
- neo-cli/config.json
- neo-cli/config.mainnet.json
- neo-cli/config.testnet.json
Add "MaxGasInvoke" to config.json
> Add "MaxGasInvoke" to config.json

- neo-cli/Services/ConsoleServiceBase.cs
Review of https://github.com/neo-project/neo-cli/pull/327
> Review of #327

- neo-cli/Shell/MainService.cs
> Fix invoke failed

- neo-cli/Extensions.cs
- neo-cli/Shell/MainService.cs
Improve select menu for choosing "y" or "yes".
> Improve select menu

- neo-cli/Shell/MainService.cs
Close https://github.com/neo-project/neo-cli/issues/473
> Prevent Invalid ip format on connected in neo-cli

- neo-cli/Shell/MainService.cs
> Printint error message when "UnlockWallet" wallet is not found

- neo-cli/protocol.json
- neo-cli/protocol.mainnet.json
- neo-cli/protocol.testnet.json
Change NEO 3 version address to 53, this will produce that neo address starts with N.
Needs https://github.com/neo-project/neo/pull/1299
Closes https://github.com/neo-project/neo/issues/993 https://github.com/neo-project/neo/issues/1017
> Remove address version config

- neo-cli/CLI/ConsolePercent.cs
- neo-cli/CLI/MainService.cs
- neo-cli/Services/ConsoleServiceBase.cs
- neo-gui/GUI/ConsoleForm.Designer.cs
- neo-gui/GUI/ConsoleForm.cs
- neo-gui/GUI/MainForm.cs
This patch improve the progress bar aspect and experience
> Improve progress bar aspect

- Dockerfile
> up dockerfile

- neo-cli/CLI/MainService.cs
Close https://github.com/neo-project/neo-node/issues/531
> Fix add address twice

- .github/workflows/dotnetcore.yml
- neo-cli/Services/ServiceProxy.cs
- neo-gui/GUI/ParametersEditor.cs
Copy of https://github.com/neo-project/neo-modules/pull/185
> Fix dotnet-format

- neo-cli/CLI/MainService.cs
Fix for test related here https://github.com/neo-project/neo-devpack-dotnet/pull/187#issuecomment-581733264
> Fix NEP5 test

- neo-cli/neo-cli.csproj
Upgrade neo to 3.0.0-CI00855 (https://github.com/neo-project/neo/pull/1400), it's necessary for test purpose.
> Upgrade neo to 3.0.0-CI00855

- neo-cli/CLI/MainService.Wallet.cs
- neo-cli/CLI/MainService.cs
- neo-cli/neo-cli.csproj
- neo-gui/GUI/DeveloperToolsForm.ContractParameters.cs
- neo-gui/GUI/MainForm.cs
> Update Neo & enable change password

- Dockerfile
The `Dockerfile` was forgotten and I just adapted it for a smooth docker build. 😄
> adapt Dockerfile to recent code changes (#536)

- neo-cli/Shell/MainService.cs
* Show `StateHeight`
@shargon @erikzhang
> [neox-2.x]show state height

- neo-cli/neo-cli.csproj
- neo-cli/protocol.json
- neo-cli/protocol.mainnet.json
- neo-cli/protocol.testnet.json
Upgrade to **Neo 2.10.3-neox-preview1**
> [neox-2.x]Upgrade to Neo 2.10.3-neox-preview1

- neo-cli/CLI/MainService.cs
Close https://github.com/neo-project/neo-modules/issues/263
> Ensure json extension in wallet

- neo-cli/CLI/MainService.cs
Synchronize changes https://github.com/neo-project/neo-vm/pull/333
> Fix engine.ResultStack.Pop()

- neo-cli/CLI/MainService.cs
- neo-cli/neo-cli.csproj
> Show invocation error

- neo-cli/neo-cli.csproj
> update to preview3

- neo-cli/CLI/MainService.Wallet.cs
update list address and list key
> update list address and list key

- neo-cli/CLI/MainService.Contracts.cs
- neo-cli/CLI/MainService.NEP5.cs
- neo-cli/CLI/MainService.Wallet.cs
add sender for `invoke`; add signers for `send`.
> add sender

- neo-cli/neo-cli.csproj
- neo-cli/protocol.json
- neo-cli/protocol.mainnet.json
> Update to 2.11.0

- neo-cli/Shell/MainService.cs
- neo-cli/neo-cli.csproj
- neo-cli/protocol.json
- neo-cli/protocol.mainnet.json
- neo-cli/protocol.testnet.json
> Merge neox-2.x to master-2.x

- neo-cli/protocol.json
- neo-cli/protocol.mainnet.json
- neo-cli/protocol.testnet.json
This PR adds a adjustable MinimumNetworkFee into protocol setting.
Related to [neo-core #1901](https://github.com/neo-project/neo/pull/1901)
> [master-2.x] Add minimum network fee

- neo-cli/Settings.cs
- neo-cli/Shell/MainService.cs
- neo-cli/config.json
- neo-cli/config.mainnet.json
- neo-cli/config.testnet.json
Need [neo#1887](https://github.com/neo-project/neo/pull/1873)
> [master-2.x]Add MaxConcurrentConnections in config.json

- neo-cli/neo-cli.csproj
- neo-cli/protocol.json
- neo-cli/protocol.mainnet.json
- neo-cli/protocol.testnet.json
This PR aims to add into protocol.json field `FreeGasChangeHeight` & should be used together with [neo-core-master-2.x Reset gas free #1888](https://github.com/neo-project/neo/pull/1888)
> [master-2.x] Add FreeGasChangeHeight

- neo-cli/CLI/MainService.Vote.cs
Close https://github.com/neo-project/neo/issues/1926
> Remove Get validators

- neo-cli/protocol.json
- neo-cli/protocol.mainnet.json
> Modify FreeGasChangeHeight

- neo-cli/protocol.testnet.json
Update testnet `FreeGasChangeHeight`
> Update testnet FreeGasChangeHeight

- neo-cli/protocol.json
- neo-cli/protocol.mainnet.json
Change FreeGasChangeHeight to 6195000 for mainnet test before FLM launch.
> Change FreeGasChangeHeight to 6195000.

- neo-cli/CLI/MainService.Contracts.cs
- neo-cli/CLI/MainService.cs
wait https://github.com/neo-project/neo/pull/2044
> Fix contract hash

- neo-cli/CLI/MainService.Vote.cs
Close https://github.com/neo-project/neo-node/issues/705
> Avoid register candidate for others

- neo-cli/neo-cli.csproj
Sync to https://github.com/neo-project/neo/pull/2179
> 3.0.0-CI01125

- neo-cli/CLI/MainService.Native.cs
- neo-cli/CLI/MainService.Wallet.cs
**list nativecontract**
before
after
**list asset**
before
after
more tests
```
----------------------------------------------------
Total:   NEO:          0     GAS:   30000019.6304478
```
```
----------------------------------------------------
Total:   NEO:      50000     GAS:       1036.8213939
```
```
----------------------------------------------------
Total:   NEO:  100000000     GAS:       30000036.821
```
```
----------------------------------------------------
Total:   NEO:  100000000     GAS:  30000060.12140309
```
```
----------------------------------------------------
Total:   NEO:          0     GAS:                  0
```
```
----------------------------------------------------
Total:   NEO:   99999000     GAS:  30000192.02140769
```
``` …
```
> More alignment

- neo-cli/CLI/MainService.Node.cs
Fix "show state" auto refresh height
> fix "show state" auto refresh

- neo-cli/config.json
- neo-cli/neo-cli.csproj
close https://github.com/neo-project/neo-node/issues/747
> fix log path

- neo-cli/CLI/MainService.cs
Fix https://github.com/neo-project/neo/issues/2380
* Fix show 0 connection when `show state`.
> get localnode after start

- neo-cli/CLI/MainService.Node.cs
- neo-cli/CLI/MainService.cs
close https://github.com/neo-project/neo-node/issues/762
> fix localnode null

- neo-cli/CLI/MainService.Wallet.cs
- neo-cli/config.json
- neo-cli/config.mainnet.json
- neo-cli/config.testnet.json
- neo-cli/neo-cli.csproj
- neo-node.sln
Sync to https://github.com/neo-project/neo/pull/2409
> Sync to Neo v3.0.0-CI01257

- neo-cli/CLI/MainService.NEP17.cs
Close https://github.com/neo-project/neo-node/issues/774#issuecomment-842807685
I think that `data` seems better at the end.
> Reorder transfer arguments

- neo-cli/CLI/MainService.Wallet.cs
> reorder send args

- Neo.ConsoleService/ConsoleServiceBase.cs
Modify paste parameter maximum input length.
> Modify the maximum input length

- neo-cli/config.fs.mainnet.json
- neo-cli/config.fs.testnet.json
- neo-cli/neo-cli.csproj
Add NeoFS side chain protocol settings, so that node can join NeoFS side chain.
> NeoFS side chain settings

- neo-cli/neo-cli.csproj
- neo-gui/GUI/MainForm.cs
Remove the sqlite as it is removed to plugin.
> remove sqlite

- .github/workflows/main.yml
- Neo.ConsoleService/Neo.ConsoleService.csproj
- neo-cli/neo-cli.csproj
- neo-gui/neo-gui.csproj
- tests/Neo.ConsoleService.Tests/Neo.ConsoleService.Tests.csproj
following https://github.com/neo-project/neo/pull/2836
> update to net7.0
