neo-project/neo-node

.travis.yml
ci/Dockerfile
ci/README.md
ci/build-and-test.sh
ci/run-tests-in-docker.sh
ci/test-neo-cli.expect

Proposal of an initial continuous integration setup using [Travis CI](https://travis-ci.org) (see also #72).
If merged and [enabled at Travis CI](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI), code pushes to GitHub will automatically build the code and run a number of tests to verify the neo-cli functionality. 
* The steps executed by Travis CI are defined in `.travis.yml`
* The proposed setup uses a Docker image based on the [microsoft/dotnet:2.0-sdk](https://hub.docker.com/r/microsoft/dotnet/) base image to build the code
* Currently 2 test stages are implemented:
* **neo-cli tests using [expect](https://linux.die.net/man/1/expect)**: these tests interacts with neo-cli like any normal user, send commands and wait for correct output. This could catch …

Initial continuous integration with Travis CI

---

neo-cli/Shell/MainService.cs

New error output: `Wallet files in db3 format are not supported, please use a .json file extension.`

Better info when trying to create .db3 wallet. Fixes #82

---

ci/test-neo-cli.expect

Changed expect timeout to 10 seconds and minor fix to resolve random errors in travis-ci test runs.

Ci expect fix

---

neo-cli/Network/RPC/RpcServerWithWallet.cs
neo-cli/Settings.cs
neo-cli/Shell/MainService.cs
neo-cli/config.json
neo-cli/config.mainnet.json
neo-cli/config.testnet.json
neo-cli/neo-cli.csproj

add RPC command `getapplicationlog`

---

neo-cli/Program.cs
neo-cli/Settings.cs
neo-cli/Shell/MainService.cs
neo-cli/config.json
neo-cli/config.mainnet.json
neo-cli/config.testnet.json
neo-cli/neo-cli.csproj

added new section in config.json:
"UnlockWallet": {
"WalletPath": "/home/user/walletpath/wallet.db3",
"WalletPassword": "SuP3r53cUr£W@l137P45Sw0rd!23!",
"IsActive": false 
}
This will allow the cli to unlock a specified wallet before start all other things.
The feature can be activated and deactivated setting IsActive property properly, with true or false.
usage:
dotnet neo-cli.dll
with screen:
screen -dmS neod dotnet neo-cli.dll
Enjoy it.
tiziano@purplesoft.io

Neo cli with daemon unlock config json

---

neo-cli/Settings.cs
neo-cli/Shell/MainService.cs
neo-cli/config.json
neo-cli/config.mainnet.json
neo-cli/config.testnet.json

start consensus at startup.
enable/disable the feature from config.json - UnlockWallet Section.
I love it for development purpose... is very useful.
Enjoy it,
tiziano@purplesoft.io

Neo cli start consensus config json

---

neo-cli/Settings.cs

This fixes inconsistency between `config.json` and `settings.cs` handling of `unlockWallet` section in `UnlockWalletSettings` method. In particular: `config.json` contains `Path` and `Password` sections but they are referenced as `WalletPath` and `WalletPassword`.
Also removes bad condition  - `section.Value` is always `null` because it doesn't contain any value only nested sections.

settings.cs fix

---

neo-cli/Network/RPC/RpcServerWithWallet.cs

This adds a RPC call to retrieve the wallet height. This helps with understanding if the wallet has caught up to the block height.
It returns 400 Access denied if a wallet is not loaded in the same way as other RPC calls.

Add getwalletheight RPC call

---

neo-cli/Shell/Coins.cs
neo-cli/Shell/MainService.cs

This PR modified claim gas operation to limited 50 claims per transaction. This may create more than 1 ClaimTransaction during 1 cmd but make it possible to claim gas from 10k transactions. Extra output is provided to show the progress.

Modify claim operation to 50 claims per tx

---

neo-cli/Shell/MainService.cs

minor update on IsStandardContract checking if contract is IsSignatureContract() or IsMultiSigContract()
Closes neo-project/neo#411

IsStandard to Script.IsStandardContract()

---

neo-cli/Services/ConsoleServiceBase.cs
neo-cli/Shell/MainService.cs

Linux users can't easily run neo-gui for deploying contracts, and it seems like neo-cli should support deploying and invoking contracts. This gives it the ability to deploy contracts and allows passing params surrounded in quotes so spaces can be included in cli commands.
This is copied from #180 but updated to work with the latest code base. I tested deploying a 38Kbyte contract. Worked nicely.

Add support for deploying contracts + initial support for invoking contracts. Also add support for quoted arguments that may contain spaces.

---

neo-cli/Settings.cs
neo-cli/Shell/Coins.cs
neo-cli/Shell/MainService.cs
neo-cli/neo-cli.csproj

Add `MaxConnectionsPerAddress` to `Settings`

---

neo-cli/Services/ConsoleServiceBase.cs

This change allows plugins to receive empty messages from the command-line, useful in a debugging scenario, where an empty line entry indicates the debugger should repeat the previous step command, or page through a disassembly dump.

allow empty console command to pass into OnCommand

---

neo-cli/Services/ConsoleServiceBase.cs

If you write `\"x` your node will killed by a `FormatException`

Fix \"x error

---

neo-cli/Shell/MainService.cs

Fix uninstall plugin (2x)

---

neo-cli/Services/ConsoleServiceBase.cs

GNU/Linux systems generally use UTF-8, not UTF-16.
Using UTF-16 may "appear" to work with ASCII characters because NULs are silently skipped by terminal emulators, but this causes problems when scripting neo-cli.
For now, I moved this configuration under Win32 condition, but I don't know what is the right thing to do with Win32. Maybe it makes sense to remove this statement altogether.

Don't hardcode System.Text.Encoding.Unicode (which is UTF-16LE) as output encoding

---

neo-cli/Shell/MainService.cs

I think that it's not necessary that neo-cli enforces a minimum fee of 0.001 on all transactions, only on those that exceed 1024 bytes.

allow free tx as default on invocations

---

neo-cli/Shell/MainService.cs

Related to https://github.com/neo-project/neo/pull/832
Close https://github.com/neo-project/neo-cli/issues/287

Ping nodes while show state

---

neo-cli/Shell/MainService.cs

Don't need at least 5 elements for the command of import multisigaddress on solo chain.

Fix import multisigaddress method on solo chain

---

neo-cli/Shell/MainService.cs

closes https://github.com/neo-project/neo-compiler/issues/149

Renaming avm to nef

---

neo-cli/Extensions.cs
neo-cli/Settings.cs

Follow up PR (neo-project/neo#851).
Use environment value of "NEO_NETWORK" to resolve which config.json should be loaded.
Especially for docker users.

load config.json with enviroment.

---

neo-cli/Shell/MainService.cs

Before:
```
block: 0/4000000/4000000  connected: 10  unconnected: 100
ip: 111.111.111.111	port: 22222	listen: 10333	height: 4000000
ip: 222.222.222.222	port: 22222	listen: 10333	height: 4000000
ip: 1.1.11.11	port: 22222	listen: 10333	height: 4000000
ip: 333.333.333.333	port: 22222	listen: 10333	height: 4000000
```
After:
```
block: 0/4000000/4000000  connected: 10  unconnected: 100
ip: 111.111.111.111	port: 22222	listen: 10333	height: 4000000
ip: 222.222.222.222	port: 22222	listen: 10333	height: 4000000
ip: 1.1.11.11     	port: 22222	listen: 10333	height: 4000000
ip: 333.333.333.333	port: 22222	listen: 10333	height: 4000000
```

Adjust the output format of show state command (2x)

---

neo-cli/Services/ConsoleServiceBase.cs
neo-cli/Shell/MainService.cs

Close https://github.com/neo-project/neo-devpack-dotnet/issues/91
Require https://github.com/neo-project/neo-devpack-dotnet/pull/109
Related to https://github.com/neo-project/neo-devpack-dotnet/issues/91
Should follow this logic
https://github.com/neo-project/neo/blob/e1fdde307153879f0a7ae64bd3e11d042284896e/neo/SmartContract/InteropService.NEO.cs#L248

Update deploy command following NEO3 schema

---

ci/Dockerfile
neo-cli/neo-cli.csproj

Close https://github.com/neo-project/neo-cli/issues/478
Require https://github.com/neo-project/neo/pull/1178
Framework updated to dotnet 3.0
Changes:
- https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0
Benchmarks
- https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-core-3-0

Upgrade dependencies and target frameworks

---

neo-cli/CLI/MainService.cs
neo-cli/Program.cs
neo-cli/Services/ConsoleServiceBase.cs

Close https://github.com/neo-project/neo-node/issues/503
Please @superboyiii @cloud8little test it
~It seems that there is a bug with linux and Console.Read~
~Bug POC:~
```
Console.ReadLine(); // Show the output
Console.Read();  // Read only one char
Console.ReadLine(); // This doesn't show the output now :S
```

Fix Console.ReadLine in linux

---

neo-cli/CLI/MainService.cs
neo-cli/neo-cli.csproj
neo-gui/GUI/DeployContractDialog.cs

Allow to compile with the last neo changes

Update neo nuget

---

README.md

Trivial change, adding these dependencies so others don't have to dig through the package repositories to find the equivalent packages.

Add dependencies on fedora

---

neo-cli/Services/ConsoleServiceBase.cs

@igormcoelho opened this issue https://github.com/neo-project/neo/issues/668 about printing neo versions on the log and @vncoelho suggested to print the git commit hash aswell.
I made a NerdBank.GitVersioning setup on the project to use a `version.json` file to define the version code (as suggested by @devhawk) and the git commit hash and save on AssemblyInformation.
This setup was made on neo and neo-vm aswell, if this PR is approved I can send PR for them so all versions will be printed with the commit hash.
I don't know if this solution satisfy all the needs presented by Igor, let me know if there is anything else I could do.

Showing version of neo and neo-vm on startup

---

neo-cli/CLI/MainService.cs
neo-cli/neo-cli.csproj
neo-gui/GUI/Wrappers/UIntBaseConverter.cs

Related to https://github.com/neo-project/neo/pull/1415

Allow to skip verification

---

neo-cli/CLI/MainService.cs

Another bug, similar to this one https://github.com/neo-project/neo-node/pull/547
before
after

Fixed GAS decimals

---

Neo.ConsoleService/CommandToken.cs
Neo.ConsoleService/ConsoleServiceBase.cs
neo-cli/CLI/MainService.cs

Close https://github.com/neo-project/neo-node/issues/556

Fix plugin commands

---

neo-cli/CLI/MainService.Contracts.cs
neo-cli/CLI/MainService.Oracle.cs
neo-cli/CLI/MainService.cs

Allow to invoke like this:
`invoke 0xae1573577a1b5b91b1649f2e54c58ff9bb51f628 "download" '["https://www.bitstamp.net/api/ticker/","bid"]' NVBTPMgBvyDLEWboCdYVbdZwSVU5R9iR5t`
And like the original version
`invoke 0xae1573577a1b5b91b1649f2e54c58ff9bb51f628 "download" '[{"type":"String","value":"https://www.bitstamp.net/api/ticker/"},{"type":"String","value":"bid"}]' NVBTPMgBvyDLEWboCdYVbdZwSVU5R9iR5t`

Oracle: Improve user experience

---

neo-cli/CLI/MainService.Wallet.cs
neo-cli/neo-cli.csproj

Password change (#561) should be harmless but I think it is advisable to make a backup before to avoid losses due to disk corruption, power failures, ...
* Needs https://github.com/neo-project/neo/pull/1627

Backup Wallet on change password

---

neo-cli/CLI/MainService.Contracts.cs
neo-cli/CLI/MainService.NEP5.cs
neo-cli/CLI/MainService.cs

BalanceOf, transfer, name and decimals

Add NEP5 commands

---

neo-cli/Settings.cs

Close https://github.com/neo-project/neo-node/issues/583

Fill default settings

---

neo-cli/CLI/MainService.Network.cs
neo-cli/CLI/MainService.Wallet.cs

Affected by https://github.com/neo-project/neo/pull/1667, we need to change from `LocalNode` to `Blockchain` to relay tx.

Fix relay tx

---

neo-cli/protocol.json
neo-cli/protocol.mainnet.json
neo-cli/protocol.testnet.json

Add fields to protocol.json

---

neo-cli/CLI/MainService.Plugins.cs
neo-cli/neo-cli.csproj

Add uninstalled plugins and descriptions on "plugins" command

---

neo-cli/CLI/MainService.cs

Change `StackItem.ToParameter().ToJson()`  to `StackItem.ToJson()` when parsing `engine.ResultStack`.

Remove `StackItem.ToParameter()`

---

neo-cli/CLI/Logger.cs
neo-cli/CLI/MainService.Plugins.cs

Close #601 
This may look stupid.🤣 Maybe we should not implement "SystemLog" as a plugin, but which needs modification from neo-core: 
```c#
public static void Log(string source, LogLevel level, object message)
{
foreach (ILogPlugin plugin in Plugin.Loggers)
plugin.Log(source, level, message);
}
```

Add description and uninstall restriction for "SystemLog"

---

neo-cli/CLI/MainService.Contracts.cs
neo-cli/CLI/MainService.Vote.cs
neo-cli/CLI/MainService.cs
neo-cli/neo-cli.csproj

Apply https://github.com/neo-project/neo/pull/1752
Apply neo-project/neo#1758
- update signers
- update nuget
- update vote commands

apply signers

---

neo-cli/CLI/MainService.Node.cs

`GetVerifiedAndUnverifiedTransactions` it's thread safe, but while printing the list, the mempool can change and show different totals from those shown in the list

Improve Show pool command

---

neo-cli/CLI/MainService.Tools.cs
neo-cli/CLI/MainService.cs

Changed some UTF8 to be StrictUTF8

Unify encoding to be Strict UTF8

---

neo-gui/GUI/InvokeContractDialog.cs

Apply https://github.com/neo-project/neo/pull/1819

Fix applicationengine.run

---

neo-cli/CLI/MainService.Contracts.cs
neo-cli/CLI/MainService.NEP5.cs
neo-cli/CLI/MainService.Vote.cs
neo-cli/CLI/MainService.cs

Fix https://github.com/neo-project/neo-node/issues/672#issuecomment-709049386

Fix to avoid duplicate error message

---

neo-cli/CLI/MainService.Contracts.cs
neo-cli/CLI/MainService.cs
neo-cli/neo-cli.csproj

Related: https://github.com/neo-project/neo/pull/2044
Close https://github.com/neo-project/neo-node/issues/685
***Please dont't merge until related PRs are all merged.***

Sync neo changes

---

neo-cli/CLI/MainService.Wallet.cs
neo-cli/CLI/MainService.cs
neo-cli/neo-cli.csproj

Close https://github.com/neo-project/neo-node/issues/690
Sync to https://github.com/neo-project/neo/pull/2119
Required: https://github.com/neo-project/neo/pull/2119

Sync to management SC

---

neo-cli/CLI/MainService.cs
neo-cli/neo-cli.csproj
neo-gui/GUI/DeployContractDialog.cs
neo-gui/GUI/ElectionDialog.cs
neo-gui/GUI/InvokeContractDialog.cs
neo-gui/GUI/MainForm.cs
neo-gui/GUI/VotingDialog.cs

Close https://github.com/neo-project/neo-node/issues/711

Neo 3.0.0-CI01152

---

neo-cli/CLI/MainService.Node.cs
neo-cli/neo-cli.csproj
neo-gui/GUI/MainForm.cs
neo-gui/GUI/MainForm.resx

Show header height when show state

Show header height when show state

---

neo-cli/CLI/MainService.Blockchain.cs
neo-cli/CLI/MainService.Contracts.cs
neo-cli/CLI/MainService.NEP17.cs
neo-cli/CLI/MainService.Network.cs
neo-cli/CLI/MainService.Node.cs
neo-cli/CLI/MainService.Wallet.cs
neo-cli/CLI/MainService.cs
neo-cli/neo-cli.csproj

~~need to add a new msg type `GetInstance `  in `LocalNode` class like this:~~
```
protected override void OnReceive(object message)
{
base.OnReceive(message);
switch (message)
{
case Message msg:
BroadcastMessage(msg);
break;
case RelayDirectly relay:
OnRelayDirectly(relay.Inventory);
break;
case SendDirectly send:
OnSendDirectly(send.Inventory);
break;
case GetInstance _:
Sender.Tell(this);
break;
}
}
```

remove singletons

---

neo-cli/CLI/MainService.cs
neo-cli/neo-cli.csproj

close https://github.com/neo-project/neo-modules/issues/526

Fix autostart

---

neo-cli/CLI/MainService.Contracts.cs
neo-cli/CLI/MainService.cs
neo-cli/neo-cli.csproj

Reference: https://github.com/neo-project/proposals/pull/136

Add update

---

neo-cli/CLI/MainService.Vote.cs

Close https://github.com/neo-project/neo-node/issues/784

fix and improve

---

neo-cli/CLI/MainService.Wallet.cs

Close https://github.com/neo-project/neo-node/issues/822

Show gas before send

---

neo-cli/CLI/MainService.Contracts.cs
neo-cli/CLI/MainService.cs

Let user be able to deploy or update contract with `data`.

Add data parameter when deploy and update contract

---

Dockerfile

Dockerfile from dotnet 6.0 image

---

neo-cli/config.testnet.json

Allow to flush the mempool in just 10 blocks.

neo-cli: tune MaxTransactionsPerBlock for testnet

---

neo-cli/config.testnet.json

Since testnet data is incompatible now becasue of the modification of native contract, we could create a new testnet `N3T5`. Wait for a better solution on native contract update.

Add new testnet network id

---

.github/workflows/docker-test.yml
Dockerfile

As mentioned [here](https://github.com/neo-project/neo/commit/ee93a8dd9a4b4fad4eb1a9a2e11ae6e06bffaf8e), I believe that **once again** the `Dockerfile` was simply ignored after the upgrade from dotnet 6 to 7.
It already happened more than once: developers change code but they simply forget to update other parts of the repo that do not fail on the build time. There are some Neo projects relying on this `Dockerfile`, especially for tests.
This PR makes the whole GitHub Action workflow fail if anything is merged and something with `Dockerfile` image is not right (e.g., wrong dotnet version, or anything like that).
The next step would be to enhance to check if the Docker image at least starts with the node.. but that's a bit more work and I haven't included it in this PR. One thing at a time. …

Update Dockerfile to use dotnet 7.0

---

neo-cli/CLI/Helper.cs
neo-cli/CLI/MainService.cs

@shargon how about updating the script checking logic before we issue the transaction from cli.

Validate before deploy update

---

.github/workflows/docker-test.yml
Dockerfile

As described [here](https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/), we followed the proper way to use dotnet docker images with `buildx` (multi-platform).

Update Dockerfile to properly enable multi platform

---

neo-cli/CLI/MainService.Wallet.cs

Related to: https://github.com/neo-project/neo/pull/2818
1. Add `cancel` command.
2. Check if aimed tx is in mempool, if it is, choose the max networkfee between the current and the aimed. If it isn't, wait for inputting networkfee manually.
3. Add a `NOP` to tx.script to ensure not rejected by consensus.
4. Return error when aimed tx is already confirmed.

add cancel command for conflict attribute

---

neo-cli/CLI/MainService.Wallet.cs

Avoid the use of the signature as https://github.com/neo-project/neo-modules/pull/837#discussion_r1358116776

Change Cancel Scope

---

neo-cli/CLI/MainService.Blockchain.cs
neo-cli/CLI/MainService.Wallet.cs

**Change Log**
- Add command `show block <index>`
- Add command `show block <hash>`
- Add command `show tx <hash>`
- Add command `show contract <name>`
- Add command `show contract <hash>`

Added blockchain show block/transactions/contracts commands
